<a href="https://colab.research.google.com/github/Szynaman123/IO/blob/master/numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
np.__version__

'1.19.5'

In [4]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_

In [5]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

In [6]:
x=np.array([1,3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


In [8]:
type(x)

numpy.ndarray

In [9]:
x.ndim

1

In [10]:
x.shape

(2,)

In [11]:
x.size

2

In [12]:
x.dtype

dtype('int64')

In [13]:
x=np.array([1.3,2.3,1.4])
x

array([1.3, 2.3, 1.4])

In [14]:
x.dtype

dtype('float64')

In [15]:
x=np.array([[1,2],[-3,1]])

In [16]:
x.ndim

2

In [17]:
x.shape

(2, 2)

In [18]:
x=np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [19]:
x.shape

(2, 3)

In [20]:
x=np.array(
    [[[4,3,1],
      [3,1,2]],
     
     [[4,1,3],
      [4,2,1]]]
    )
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [21]:
x.ndim

3

In [22]:
print(x)

[[[4 3 1]
  [3 1 2]]

 [[4 1 3]
  [4 2 1]]]


In [23]:
x.shape

(2, 2, 3)

In [24]:
A=np.array([1,2,3])
A.dtype

dtype('int64')

In [25]:
A=np.array([1,2,3],dtype='float')
A.dtype

dtype('float64')

In [26]:
A

array([1., 2., 3.])

In [27]:
A=np.array([1,2,3],dtype='complex')
A.dtype

dtype('complex128')

In [28]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [29]:
A=np.array([1.1,2.2,3.3],dtype='int')
A.dtype

dtype('int64')

In [30]:
A

array([1, 2, 3])

In [31]:
A=np.array([24,120,230],dtype=np.uint8)
A.dtype

dtype('uint8')

In [32]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
np.full(shape=(3,3),fill_value=4,dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(start=0,stop=1,step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [36]:
np.linspace(start=0,stop=1,num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [37]:
A=np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
A.reshape((-1,3))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [39]:
A=np.array([3,1,4,2])

In [40]:
B=np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [41]:
A+B

array([6, 0, 7, 4])

In [42]:
A-B

array([0, 2, 1, 0])

In [43]:
A*B

array([ 9, -1, 12,  4])

In [44]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [45]:
A+3

array([6, 4, 7, 5])

In [46]:
X=np.array([[1,3],[-2,0]])
Y=np.array([[6,0],[-1,2]])
print(X,'\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [47]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [48]:
X@Y

array([[  3,   6],
       [-12,   0]])

In [49]:
np.random.seed(0)

In [50]:
np.random.randn(10,4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275]])

In [51]:
np.random.rand(10,3)

array([[0.31542835, 0.36371077, 0.57019677],
       [0.43860151, 0.98837384, 0.10204481],
       [0.20887676, 0.16130952, 0.65310833],
       [0.2532916 , 0.46631077, 0.24442559],
       [0.15896958, 0.11037514, 0.65632959],
       [0.13818295, 0.19658236, 0.36872517],
       [0.82099323, 0.09710128, 0.83794491],
       [0.09609841, 0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552, 0.73926358],
       [0.03918779, 0.28280696, 0.12019656]])

In [52]:
np.random.randint(low=10,high=101,size=20)

array([33, 69, 12, 72, 45, 77, 92, 56, 30, 91, 60, 37, 24, 51, 68, 75, 46,
       20, 96, 53])

In [53]:
np.random.choice([4,2,1,4])

4

In [54]:
data= np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.random.shuffle(data)

In [56]:
print(data)

[5 1 4 9 8 6 7 0 3 2]


In [57]:
np.exp(1)

2.718281828459045

In [58]:
np.sqrt(9)

3.0

In [59]:
np.all([2,3,1])

True

In [60]:
A= np.random.rand(5)

In [61]:
A

array([0.02010755, 0.82894003, 0.00469548, 0.67781654, 0.27000797])

In [62]:
np.argmax(A)

1

In [63]:
np.argsort(A)

array([2, 0, 4, 3, 1])

In [64]:
np.mean(A)

0.36031351231715975

In [65]:
np.median(A)

0.27000797319216485

In [66]:
np.std(A)

0.33786931210140275

In [67]:
A=np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [70]:

A=np.arange(start=-10,stop=10,step=0.5)

In [71]:
A=A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [72]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [73]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])